# Hyperliquid WebSocket Proxy Configuration

# Server configuration
server:
  host: "0.0.0.0"     # Interface to bind to (0.0.0.0 for all interfaces)
  port: 8080          # Port to listen on

# Hyperliquid API configuration
hyperliquid:
  mainnet_url: "wss://api.hyperliquid.xyz/ws"
  testnet_url: "wss://api.hyperliquid-testnet.xyz/ws"
  network: "mainnet"  # "mainnet" or "testnet"

# Logging configuration
logging:
  level: "debug"       # debug, info, warn, error
  format: "text"      # text or json

# Proxy configuration
proxy:
  max_clients: 1000            # Maximum number of concurrent WebSocket clients
  enable_heartbeat: true       # Enable connection heartbeat monitoring
  heartbeat_interval: 30       # Heartbeat interval in seconds
  reconnect_max_retries: 5     # Max reconnection attempts to Hyperliquid
  reconnect_interval: 5        # Reconnection interval in seconds
  buffer_size: 1024           # Message buffer size
  
  # Configuration pour utiliser le node local au lieu de l'API WebSocket
  enable_local_node: true
  local_node_data_path: "/var/lib/docker/volumes/node_hl-data-mainnet/_data"  # Real path to your node data 