version: '3.8'

services:
  hyperliquid-proxy:
    build: .
    container_name: hyperliquid-ws-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config.yaml:ro
      # Accès aux données du node Hyperliquid local (read-only)
      - /var/lib/docker/volumes/node_hl-data-mainnet/_data:/var/lib/docker/volumes/node_hl-data-mainnet/_data:ro
    command: ["-config", "/config.yaml", "-log-level", "info"]
    environment:
      - TZ=Europe/Paris
    # Utiliser root pour accéder aux volumes Docker du node
    user: "0:0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5" 